### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by AnnaBjerk** [bjerkio/website#137]
#### Work items

 - [ ] Decide tests for _common components_
 - [ ] Decide tests for accessibility (e.g. [pa11y](https://pa11y.org/))
 - [ ] Create a CONTRIBUTING.md for this repo
 - [ ] Identify preview customers
 - [x] 👆 Figure out the _performance budget_
 - [x] Refactor `sx` usage #129
 - [x] Remove Sanity Plugin and studio #130
 - [x] Rename all assets #131
 - [x] Add `gatsby-image` #132
 - [ ] Clean up deprecated packages #135
