### ISSUE TITLE
Implement the «Metadata» concept on our website

### ISSUE THREAD

**Issue by simenandre** [bjerkio/website#623]
For many years, the word we've used for things like `title`, `description` and `keywords` in our `<meta />`-tags has been SEO or Search Engine Optimalization. Our website is tampered with that as well, however, it's not _really_ the content we're adding – is not only search engine related stuff. We need to rethink this.

Let me introduce _Metadata_. What does it contain?

See a visual representation here:
https://www.figma.com/file/wGvu0REY9x3euk0oEWzNxk/Bjerk-Playground?type=design&node-id=2472-2855&mode=design&t=PvdQ5Nc8rCKrWd6U-4

Here's a Typescript interface:

```typescript
export interface Metadata {
  /**
   * Fields are used by search engines to index your site.
   */
  searchEngine: {
    /**
     * The ideal length for a title is approx. 60 characters.
     * When exceeding this limit, search engines will truncate the title.
     */
    title: string;

    /**
     * The ideal length is between 70 and 155 characters.
     * Minium length is 70 characters.
     * When exceeding this limit, search engines will truncate the description.
     */
    description: string;
  };

  /**
   * Fields are used by social media platforms to display your site.
   */
  socialMedia: {
    /**
     * The ideal length for a title is approx. 47 characters.
     * When exceeding this limit, platforms will truncate the title.
     *
     * LinkedIn will truncate the title at 119 characters.
     */
    title: string;

    /**
     * Should not exceed 85 characters to fit most platforms.
     */
    description: string;

    /**
     * The ideal size is 1200 x 630 pixels.
     * When you are providing more than one image, the first image will be used, but some
     * platforms will allow the user to choose which image to use.
     */
    images: Picture[];
  };
}
```

We have a [component for Metadata already](https://github.com/bjerkio/website/blob/main/src/components/metadata.svelte), but that is not standardized enough for us to uniquely add the data I've exemplified above for each page. Another issue is that in Sanity, [we have an object called _SEO_](https://github.com/bjerkio/studio/blob/main/schemas/objects/seo.ts) which we are [parsing in our website](https://github.com/bjerkio/website/blob/main/src/data/types.ts).

### Tasks to make it easier to add _metadata_ in code

- [x] Refactor the Metadata-component to have similar/same properties as the Metadata interface
- [x] Remove `MetaTagsProps` thing?

### Tasks to make it easier to add metadata in Sanity

- [ ] Add a new object in Sanity that is the same [as the design](https://www.figma.com/file/wGvu0REY9x3euk0oEWzNxk/Bjerk-Playground?type=design&node-id=2472-2855&mode=design&t=PvdQ5Nc8rCKrWd6U-4)
- [ ] Implement the object in projects/cases
- [ ] Add a Zod model for Metadata in website
- [ ] Remove `seo` input. The Metadata component inputs and Metadata object from Sanity will be the same/similar, so they should be compatible

**Comment by simenandre** [comment]
A key thing I left out. On a website, there are more than one title:

- Title for the browser: `<title>Hello world</title>`
- Title for the search engine
- Title for social media (which can be more than one)

We probably need to differentiate between these in our `Metadata` component.
