### ISSUE TITLE
Release our new website! 🎉

### ISSUE THREAD

**Issue by cobraz** [bjerkio/website#90]
### Goal

Our main goal is to grow, engage and satisfy our customer base with a visually and textually improved website for Bjerk.

## Team

- Design: @AnneMatilde 
- Engineers: @dkostenko-bjerk @cobraz 
- PM: @AnnaBjerk 

#### Design and specification 📔

- [x] Design
  - [x] Figure out if we want dark mode (#101)
- [x] Identify the QA checks
  - [x] Lighthouse (Goal: Check every page, at every push, #75)
  - [x] Decide CI: Build, ~~Test~~, Lint
 

#### Engineering ⚙️

- [x] Add customer references/projects (#88, #87, #86, #85)
- [x] Add content to the about, contact, services pages (#103, #104, #105)
- [x] Add mobile view (#97)
- [x] Decide if we need Sanity (#74)
- [x] Fix the video fitting (#63)
- [x] Navigation bar stuff (#71, #70)
- [x] Reposition (#69, #68, #89)
- [x] Fix text/Font styling (#67, #66)
- [x] Add tree image at the bottom (#96)
- [x] ~~Localization (#23)~~ 
- [x] Close all TODO tasks (#82)
- [x] Styling (#89)
- [x] Decide what to do with #106 
- [x] Fix font issue #116
- [x] Fix scaling issue #117 `waiting for review`
- [x] Fix inner-container max-width #126 
- [x] Remove language selector. #140

#### Release planning

- [x] ~~Create social media campaign~~
- [x] Ship it 🚀
- [ ] Share it 🚀

**Comment by cobraz** [comment]
Re «Identify preview customers»; It would be nice to get some feedback from some of our clients, which is why I had that in our list. What do you think, @seacurrent?
